### ISSUE TITLE
How to browse pptx by PHPPresentation

### ISSUE THREAD

**Issue by qlzxmacheng** [PHPOffice/PHPPresentation#386] opened 2017-08-01 03:02 UTC
I need browse pptx on the Google Browser ,  but I use Sample 12 Reader PowerPoint2007 , only look tree , I need  browse pptx and it can play animation in the pptx , can you help me ? Thinks

**Comment by Progi1984** [comment] 2017-08-01 07:57
@qlzxmacheng What is the Google Browser ?

You want to view a presentation (pptx or odp) in a browser ?

**Comment by qlzxmacheng** [comment] 2017-08-01 08:24
yes ,  I want to  view a ppt in a browser ,  such as ppt -> H5  ,  Can you help me ?my english is not good...

**Comment by qlzxmacheng** [comment] 2017-08-01 08:27
@Progi1984  Thinks for you,  I want to view a ppt in a browser, such as ppt -> h5 in a brower, Can you help me?  my English is very bad......

**Comment by Progi1984** [comment] 2017-08-01 08:34
@qlzxmacheng What is h5 ?

What is your preffered language (french, for me) ?

**Comment by qlzxmacheng** [comment] 2017-08-01 08:38
@Progi1984 Sorry , I am Chinese,   H5 is  html5 ,  i would like to view a ppt in the browser,  Can you help me?

**Comment by Progi1984** [comment] 2017-08-01 08:44
Duplicates #221

**Comment by qlzxmacheng** [comment] 2017-08-01 08:46
thank you very much

**Comment by Progi1984** [comment] 2017-08-01 08:47
Duplicate of #221

**Closed** 2017-08-01 08:47 UTC

**Comment by qlzxmacheng** [comment] 2017-08-01 08:50
Do you have a good method to solve this problem?

**Comment by Progi1984** [comment] 2017-08-01 08:59
Yes, write a PR with a HTML Writer :) or wait for it :)

**Comment by qlzxmacheng** [comment] 2017-08-01 09:03
thank you

**Comment by sotirelisc** [comment] 2021-06-28 08:20
Are there any updates on this?

Thanks.
