### ISSUE TITLE
Multiple charts

### ISSUE THREAD

**Issue by dormadekhin** [PHPOffice/PHPPresentation#712] opened 2022-07-02 15:32 UTC
Hello!
How to add combine multiple graphs in one area?
like here
![image](https://user-images.githubusercontent.com/32381310/177006912-1081ad11-e783-415d-9681-9e567606ce78.png)

**Comment by pal-software** [comment] 2022-07-03 06:47
Sample was here: #672

**Comment by Progi1984** [comment] 2024-09-02 08:40
Duplicate of #672

**Closed by Progi1984** 2024-09-02 08:40 UTC
